SELECT CLIENT.NAME, DATEDIFF('mm', START_DATE, FINISH_DATE) AS MONTH_COUNT
FROM PROJECT
INNER JOIN CLIENT ON CLIENT.ID = PROJECT.CLIENT_ID
INNER JOIN (
    SELECT MAX(DATEDIFF('mm', START_DATE, FINISH_DATE)) AS MAX_MONTH_COUNT
    FROM PROJECT
) AS MAX_MONTHS ON DATEDIFF('mm', PROJECT.START_DATE, PROJECT.FINISH_DATE) = MAX_MONTHS.MAX_MONTH_COUNT