SELECT CLIENT.NAME, COUNT(PROJECT.ID) AS PROJECT_COUNT
FROM PROJECT
INNER JOIN CLIENT ON PROJECT.CLIENT_ID = CLIENT.ID
GROUP BY CLIENT_ID

HAVING COUNT(PROJECT.ID) = (
    SELECT MAX(PROJECT_COUNT)
    FROM(SELECT COUNT(PROJECT.ID) AS PROJECT_COUNT
         FROM PROJECT
         GROUP BY CLIENT_ID)
);