SELECT PROJECT_ID AS NAME, (PRICE* MONTH_COUNT) AS PRICE
FROM (SELECT PROJECT_ID, SUM(SALARY) as PRICE, MONTH_COUNT
                FROM (SELECT PROJECT_WORKER.PROJECT_ID, PROJECT_WORKER.WORKER_ID, WORKER.SALARY, DATEDIFF('mm', START_DATE, FINISH_DATE) AS MONTH_COUNT
                        FROM PROJECT_WORKER
                        INNER JOIN WORKER ON WORKER.ID = PROJECT_WORKER.WORKER_ID
                        INNER JOIN PROJECT ON PROJECT.ID= PROJECT_WORKER.PROJECT_ID)
                        WHERE PROJECT_ID IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
                        GROUP BY PROJECT_ID);